### PR TITLE
Mark actions as done

### PR DESCRIPTION
**Pull request by sah**
Allow users to mark actions done (issue #36). 

Unstyled at this point, but the functionality should be correct. Check boxes appear roughly where indicated in the mock-up.

### CODE REVIEW

**Comment by sah** [comment]
@sahadeva can you handle styling something like this? I'd have to go learn more CSS.

**Comment by sahadeva** [comment]
@sah did you see this branch? https://github.com/IndivisibleTemplate/BasicTemplate/tree/checkmarks

**Comment by sah** [comment]
I hadn't! I'm going to merge that in here and see if I can wire it all up.

**Comment by sah** [comment]
That was faster than I expected! Everything is working together and ready for a look.

**Comment by sah** [comment]
I think this is probably ready to go. Have a look!

**Comment by sahadeva** [comment]
@sah Tested it on a live github site at sahadeva.github.io all seems to be working correctly 💯 🥇 

Thank you so much!

**Pull request merged**
