### PR TITLE
Adding sitemap

### PR DESCRIPTION
**Pull request by sah**
Adding sitemap (issue #2), using the jekyll-sitemap plugin

### CODE REVIEW

**Comment by sahadeva** [comment]
@sah Awesome! Quick question: How does the gemfile upgrade actually work? I assume that GitHub pages has a built script or something so when you add a new gem to the gemfile it updates the site?

**Comment by sah** [comment]
I'm new to GitHub Pages, so I'm not sure how this works. Either it has a build script like you suggest, or it just relies on the contents of the `_site` directory, which has to be built and committed on the gh-pages branch.

**Comment by sah** [comment]
Did some research, and I'm pretty sure this will work, because the plugin is in the set GitHub supports: https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

**Comment by sahadeva** [comment]
@sah OK awesome. I'm going to set this up in a new repo and push to GitHub pages and test asap. Will update soon!

**Comment by wa9indivisibles** [comment]
is this feature ready for consumption yet?

**Comment by sah** [comment]
I think this is ready to merge. @sahadeva, any objections?

**Comment by sahadeva** [comment]
@sah Just merged! Apologies for the delay - just went through an apartment move! 

@sah also, thanks so much!

**Review by sahadeva — COMMENTED** [review]
great!

**Pull request merged**
