### PR TITLE
Bug/45 email code

### PR DESCRIPTION
**Pull request by kfitzpatrick**
Addresses #45

### CODE REVIEW

**Comment by kfitzpatrick** [comment]
OK that's strange. Are my CMS changes getting pushed back into master?

**Comment by kfitzpatrick** [comment]
Perhaps those published changes should be going into a branch called `pages`.
As a user, I'm not expecting that my CMS is committing directly to `master`, which I think of as the template branch. Do I need to change my mental model?

**Comment by kfitzpatrick** [comment]
For the moment I'm going to rebase out those changes for the purposes of a clean PR.

**Comment by kfitzpatrick** [comment]
OK, I got rid of those CMS commits.

**Comment by kfitzpatrick** [comment]
Looks like that made it pick up some some other changes. I'll fix this up after I get some clarification from @sahadeva at our 5:00 PDT call

**Review by sahadeva — APPROVED** [review]
Awesome! 👍 Thank you @kfitzpatrick !

**Comment by kfitzpatrick** [comment]
Closed in favor of @sahadeva's commit.

**Pull request closed without merging**
