### PR TITLE
Removing _site

### PR DESCRIPTION
**Pull request by sah**
This jekyll-generated directory shouldn't be in git. See http://stackoverflow.com/a/31871892

### CODE REVIEW

**Comment by kfitzpatrick** [comment]
Totally agreed

**Comment by kfitzpatrick** [comment]
👍

**Comment by kfitzpatrick** [comment]
Let's merge this in as soon as possible. Will this require a different branch for the github pages that siteleaf publishes to?

**Comment by sahadeva** [comment]
@sah @kfitzpatrick done. The `_site/feed.xml` file should also not be there either right? I got a merge conflict when I pulled down locally: `CONFLICT (modify/delete): _site/feed.xml deleted in cccc7ac8567b8ba152ca4f8bd09d94a1b536658c and modified in HEAD. Version HEAD of _site/feed.xml left in tree.` I deleted the `_site/feed.xml` file and pushed up to master.

**Comment by sahadeva** [comment]
@sah I wonder if new Repos are not getting any default content when the set up a site now? E>g. http://isj-staging.wastecan.com/

screen shot 2017-04-20 at 4 29 10 pm

**Comment by sah** [comment]
@sahadeva I don't think this would cause default content to be removed. If there were a problem, I'd expect no site at all.

**Pull request merged**
